Repository infinum/eightshift-docs, pull requests merged in 2020-02, with the labels that each got.

#13 Setup theme & plugin landing pages / categories
  docs/boilerplate-index.md
  docs/boilerplate-plugin-index.md
  docs/boilerplate/instalation-and-requirements.md
  docs/plugin-index.md
  docs/plugin/instalation-and-requirements.md
  docs/theme-index.md
  docs/theme/theme-features.md
  website/sidebars.json
  website/siteConfig.js
Labels: documentation

#16 Add a DI container usage chapter
  docs/libs/di-container.md
Labels: documentation, enhancement

#20 Replace class with className
  website/pages/en/documentation.js
  website/pages/en/getting-started.js
  website/pages/en/index.js
Labels: bug

#14 Custom and Icon font chapters
  docs/guides/custom-fonts.md
  docs/guides/icon-fonts.md
  website/sidebars.json
Labels: documentation

#18 Example - Custom post types
  docs/libs/custom-post-type.md
  docs/libs/rest-routes-example.md
  website/sidebars.json
Labels: documentation

#23 Fix a minor typo in the DI documentation
  docs/guides/di-container.md
Labels: bug
