Repository infinum/eightshift-docs, pull requests merged in 2021-01, with the labels that each got.

#59 Feature/updates
  website/docs/basics/block-structure.md
  website/docs/basics/blocks-component-in-block.md
  website/docs/basics/blocks-component-structure.md
  website/docs/basics/blocks-hooks.md
  website/docs/basics/blocks-important.md
  website/docs/basics/blocks-intro.md
  website/docs/basics/blocks-patterns.md
  website/docs/basics/blocks-special-use-cases.md
  website/docs/basics/blocks-storybook.md
  website/docs/basics/blocks-transforms.md
  website/docs/basics/blocks-variations.md
  website/sidebars.js
Labels: documentation

#60 Feature/updates
  website/docs/basics/autowiring.md
  website/docs/basics/blocks-component-in-block.md
  website/docs/basics/blocks-storybook.md
  website/docs/basics/browser-sync.md
  website/docs/basics/extending-classes.md
  website/docs/basics/global-settings.md
  website/docs/basics/helpers-scss.md
  website/docs/basics/library.md
  website/docs/basics/manifest.md
  website/docs/basics/namespaces.md
  website/docs/basics/wp-cli.md
  website/docusaurus.config.js
  website/package-lock.json
  website/src/scss/utils/_colors.scss
  website/src/theme/components/markdown/markdown.scss
  website/src/theme/prism-include-languages.js
  website/src/theme/sections/foot/foot.js
Labels: documentation

#62 Broken links to theme / plugin
  website/docs/requirements.md
Labels: bug

#61 Feature/helper
  website/docs/advanced/additional-libraries.md
  website/docs/basics/helpers-javascript.md
Labels: improvement
