Repository infinum/eightshift-docs, pull requests merged in 2022-03, with the labels that each got.

#135 Feature/update docusaurus
  .github/workflows/documentation.yml
  .gitignore
  website/blog/2022-01-20-initial-setup.md
  website/blog/2022-01-21-components-and-blocks.md
  website/blog/authors.yml
  website/docs/basics/backend.md
  website/docs/basics/blocks-component-in-block.md
  website/docs/basics/blocks-wrapper.md
  website/docs/basics/frontend.md
  website/docs/legacy/v4/guides/rest-intro.md
  website/docs/legacy/v4/theme.md
  website/docs/legacy/v5/plugin.md
  website/docs/legacy/v5/theme.md
  website/docs/plugin.md
  website/docs/theme.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/sidebars.js
  website/src/scss/application.scss
  website/src/scss/utils/_defaults.scss
  website/src/scss/utils/_shared-variables.scss
  website/src/theme/SearchBar/index.d.ts
  website/src/theme/SearchBar/index.js
  website/src/theme/SearchBar/styles.css
  website/src/theme/SearchBar/styles.module.css
  website/src/theme/components/blog-layout/blog-layout.scss
  website/src/theme/components/blog-post-page/blog-post-page.scss
  website/src/theme/components/blog-sidebar/blog-sidebar.scss
  website/src/theme/components/navbar-sidebar/navbar-sidebar.scss
  website/src/theme/components/pagination/pagination.scss
  website/src/theme/prism-include-languages.js
  website/src/theme/sections/features/features.scss
  website/src/theme/sections/foot/foot.scss
  website/src/theme/sections/footer/footer.scss
  website/src/theme/sections/get-started/get-started.scss
  website/src/theme/sections/showcase-grid/showcase-grid.scss
  website/static/fonts/IBMPlexMono-Medium.woff
  website/static/fonts/IBMPlexMono-Medium.woff2
  website/static/fonts/IBMPlexSans-LightItalic.woff
  website/static/fonts/IBMPlexSans-LightItalic.woff2
  website/static/fonts/IBMPlexSans-Medium.woff
  website/static/fonts/IBMPlexSans-Medium.woff2
  website/static/fonts/IBMPlexSans-SemiBold.woff
  website/static/fonts/IBMPlexSans-SemiBold.woff2
  website/static/img/blog/components.png
  website/static/img/blog/setup-1.png
  website/static/img/blog/setup-2.png
Labels: enhancement

#142 Improve landing page copy
  website/src/theme/sections/features/features.js
  website/src/theme/sections/get-started/get-started.js
  website/src/theme/sections/panels/panels.js
  website/src/theme/sections/why/why.js
Labels: enhancement

#146 Feature/blog posts
  website/blog/2022-03-03-adding-blocks-wpcli.md
Labels: enhancement

#149 Blog/modifying blocks
  website/blog/2022-03-04-modifying-blocks.md
  website/static/img/blog/color-theme-change.gif
  website/static/img/blog/color-theme-examples.png
  website/static/img/blog/color-theme-options.png
Labels: enhancement

#151 Import useState, useEffect in Showcase grid
  website/src/theme/sections/showcase-grid/showcase-grid.js
Labels: bug

#153 Fix spacings and broken links
  website/blog/2022-03-03-adding-blocks-wpcli.md
  website/docs/basics/architecture-concepts.md
Labels: enhancement, bug
