Repository infinum/eightshift-docs, pull requests merged in 2024-02, with the labels that each got.

#248 Add blog post about I18n
  website/blog/2024-02-01-making-your-project-multilingual.md
Labels: enhancement

#305 SASS docs relocation and cleanup + package update
  website/docs/basics/library.md
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/pages/sass.js
Labels: dependencies, enhancement

#306 Fix missing links
  website/blog/2022-04-08-adding-fonts.md
  website/docs/basics/fonts.md
  website/docs/basics/helpers-scss.md
  website/docs/basics/writing-styles.md
  website/docs/legacy/v4/advanced/sass-docs.md
  website/docs/legacy/v5/basics/fonts.md
  website/docs/legacy/v5/basics/helpers-scss.md
  website/docs/legacy/v5/basics/library.md
  website/docs/legacy/v5/basics/writing-styles.md
  website/docs/legacy/v6/basics/fonts.md
  website/docs/legacy/v6/basics/helpers-scss.md
  website/docs/legacy/v6/basics/library.md
  website/docs/legacy/v6/basics/writing-styles.md
  website/docs/legacy/v7/basics/fonts.md
  website/docs/legacy/v7/basics/helpers-scss.md
  website/docs/legacy/v7/basics/library.md
  website/docs/legacy/v7/basics/writing-styles.md
  website/docs/legacy/v8/basics/fonts.md
  website/docs/legacy/v8/basics/helpers-scss.md
  website/docs/legacy/v8/basics/library.md
  website/docs/legacy/v8/basics/writing-styles.md
Labels: bug

#310 Fix wrong note display
  website/blog/2024-02-29-tips-useful-features.md
Labels: blog
